### ISSUE TITLE
[BUG] - Links on Homepage

### ISSUE THREAD

**Issue by leowilkin** [leowilkin/concepto-docs#2]
https://concepto-docs.vercel.app/

- The `About` link doesn't link to the about page.
- Currently links to self-hosted

**Also** - i8tn in French needs to be changed to update this,

**Comment by Mttgo** [comment]
I fixed it. About button was linked to self-hosted. fixed it to link to /about/what-is-concepto

**Comment by leowilkin** [comment]
Thanks @Mttgo

**Comment by leowilkin** [comment]
All good
